/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthenticatedSetupCompleteRouteImport } from './routes/_authenticated/_setup-complete'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedSetupCompleteIndexRouteImport } from './routes/_authenticated/_setup-complete/index'
import { Route as AuthenticatedSetupCompleteAccountIndexRouteImport } from './routes/_authenticated/_setup-complete/account/index'
import { Route as AuthenticatedSetupCompleteAccountBillingIndexRouteImport } from './routes/_authenticated/_setup-complete/account/billing/index'
import { Route as AuthenticatedSetupCompleteAccountBillingCheckoutSuccessRouteImport } from './routes/_authenticated/_setup-complete/account/billing/checkout-success'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSetupCompleteRoute =
  AuthenticatedSetupCompleteRouteImport.update({
    id: '/_setup-complete',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSetupCompleteIndexRoute =
  AuthenticatedSetupCompleteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSetupCompleteRoute,
  } as any)
const AuthenticatedSetupCompleteAccountIndexRoute =
  AuthenticatedSetupCompleteAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedSetupCompleteRoute,
  } as any)
const AuthenticatedSetupCompleteAccountBillingIndexRoute =
  AuthenticatedSetupCompleteAccountBillingIndexRouteImport.update({
    id: '/account/billing/',
    path: '/account/billing/',
    getParentRoute: () => AuthenticatedSetupCompleteRoute,
  } as any)
const AuthenticatedSetupCompleteAccountBillingCheckoutSuccessRoute =
  AuthenticatedSetupCompleteAccountBillingCheckoutSuccessRouteImport.update({
    id: '/account/billing/checkout-success',
    path: '/account/billing/checkout-success',
    getParentRoute: () => AuthenticatedSetupCompleteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedSetupCompleteIndexRoute
  '/callback': typeof CallbackRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/account/': typeof AuthenticatedSetupCompleteAccountIndexRoute
  '/account/billing/checkout-success': typeof AuthenticatedSetupCompleteAccountBillingCheckoutSuccessRoute
  '/account/billing/': typeof AuthenticatedSetupCompleteAccountBillingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedSetupCompleteIndexRoute
  '/callback': typeof CallbackRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/account': typeof AuthenticatedSetupCompleteAccountIndexRoute
  '/account/billing/checkout-success': typeof AuthenticatedSetupCompleteAccountBillingCheckoutSuccessRoute
  '/account/billing': typeof AuthenticatedSetupCompleteAccountBillingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_authenticated/_setup-complete': typeof AuthenticatedSetupCompleteRouteWithChildren
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/_setup-complete/': typeof AuthenticatedSetupCompleteIndexRoute
  '/_authenticated/_setup-complete/account/': typeof AuthenticatedSetupCompleteAccountIndexRoute
  '/_authenticated/_setup-complete/account/billing/checkout-success': typeof AuthenticatedSetupCompleteAccountBillingCheckoutSuccessRoute
  '/_authenticated/_setup-complete/account/billing/': typeof AuthenticatedSetupCompleteAccountBillingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/setup'
    | '/account/'
    | '/account/billing/checkout-success'
    | '/account/billing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/setup'
    | '/account'
    | '/account/billing/checkout-success'
    | '/account/billing'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/callback'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/verify-email'
    | '/_authenticated/_setup-complete'
    | '/_authenticated/setup'
    | '/_authenticated/_setup-complete/'
    | '/_authenticated/_setup-complete/account/'
    | '/_authenticated/_setup-complete/account/billing/checkout-success'
    | '/_authenticated/_setup-complete/account/billing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/_setup-complete': {
      id: '/_authenticated/_setup-complete'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedSetupCompleteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_setup-complete/': {
      id: '/_authenticated/_setup-complete/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedSetupCompleteIndexRouteImport
      parentRoute: typeof AuthenticatedSetupCompleteRoute
    }
    '/_authenticated/_setup-complete/account/': {
      id: '/_authenticated/_setup-complete/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedSetupCompleteAccountIndexRouteImport
      parentRoute: typeof AuthenticatedSetupCompleteRoute
    }
    '/_authenticated/_setup-complete/account/billing/': {
      id: '/_authenticated/_setup-complete/account/billing/'
      path: '/account/billing'
      fullPath: '/account/billing/'
      preLoaderRoute: typeof AuthenticatedSetupCompleteAccountBillingIndexRouteImport
      parentRoute: typeof AuthenticatedSetupCompleteRoute
    }
    '/_authenticated/_setup-complete/account/billing/checkout-success': {
      id: '/_authenticated/_setup-complete/account/billing/checkout-success'
      path: '/account/billing/checkout-success'
      fullPath: '/account/billing/checkout-success'
      preLoaderRoute: typeof AuthenticatedSetupCompleteAccountBillingCheckoutSuccessRouteImport
      parentRoute: typeof AuthenticatedSetupCompleteRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedSetupCompleteRouteChildren {
  AuthenticatedSetupCompleteIndexRoute: typeof AuthenticatedSetupCompleteIndexRoute
  AuthenticatedSetupCompleteAccountIndexRoute: typeof AuthenticatedSetupCompleteAccountIndexRoute
  AuthenticatedSetupCompleteAccountBillingCheckoutSuccessRoute: typeof AuthenticatedSetupCompleteAccountBillingCheckoutSuccessRoute
  AuthenticatedSetupCompleteAccountBillingIndexRoute: typeof AuthenticatedSetupCompleteAccountBillingIndexRoute
}

const AuthenticatedSetupCompleteRouteChildren: AuthenticatedSetupCompleteRouteChildren =
  {
    AuthenticatedSetupCompleteIndexRoute: AuthenticatedSetupCompleteIndexRoute,
    AuthenticatedSetupCompleteAccountIndexRoute:
      AuthenticatedSetupCompleteAccountIndexRoute,
    AuthenticatedSetupCompleteAccountBillingCheckoutSuccessRoute:
      AuthenticatedSetupCompleteAccountBillingCheckoutSuccessRoute,
    AuthenticatedSetupCompleteAccountBillingIndexRoute:
      AuthenticatedSetupCompleteAccountBillingIndexRoute,
  }

const AuthenticatedSetupCompleteRouteWithChildren =
  AuthenticatedSetupCompleteRoute._addFileChildren(
    AuthenticatedSetupCompleteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedSetupCompleteRoute: typeof AuthenticatedSetupCompleteRouteWithChildren
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSetupCompleteRoute: AuthenticatedSetupCompleteRouteWithChildren,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
