/**
 * User error codes
 */
export const USER_ERROR_CODE = {
  USER_CREATE_FAILED: "USER_CREATE_FAILED",
  USER_DELETE_FAILED: "USER_DELETE_FAILED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_UPDATE_FAILED: "USER_UPDATE_FAILED",
} as const;
