import type { Metadata } from "next";
import localFont from "next/font/local";
import "@repo/ui/globals.css";
import { ConvexClientProvider } from "@/providers/convex";
import { ThemeProvider } from "@/providers/theme";

const fontSans = localFont({
	src: "./fonts/InterVariable.woff2",
	variable: "--font-sans",
});

const fontMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-mono",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${fontSans.variable} ${fontMono.variable} font-sans antialiased`}
			>
				<ConvexClientProvider>
					<ThemeProvider>{children}</ThemeProvider>
				</ConvexClientProvider>
			</body>
		</html>
	);
}
