import type { Metadata } from "next";
import localFont from "next/font/local";
import "@repo/ui/globals.css";
import "@/styles/globals.css";
import {
	ConditionalUserMenu,
	DesktopClassSync,
	ElectronWindow,
} from "@/features/shared/components";
import {
	AuthProvider,
	ConvexClientProvider,
	SetupGuard,
	ThemeProvider,
} from "@/features/shared/providers";

const fontSans = localFont({
	src: "../fonts/InterVariable.woff2",
	variable: "--font-sans",
});

const fontMono = localFont({
	src: "../fonts/GeistMonoVF.woff",
	variable: "--font-mono",
});

/**
 * The Electron preload has already exposed `window.desktop` by the time any
 * page script runs, so tagging the root element here — before React renders —
 * means desktop styling is applied on the first paint, with no flash and no
 * hydration mismatch (`<html>` is marked `suppressHydrationWarning`).
 *
 * The overlay state is read here too, not just in `DesktopClassSync`: settling
 * it in an effect would let the first paint reserve the wrong titlebar inset.
 */
const DESKTOP_ROOT_CLASS_SCRIPT = `(function(){var d=window.desktop;if(!d)return;var c=document.documentElement.classList;c.add("electron","electron-"+d.platform);var o=navigator.windowControlsOverlay;if(o&&o.visible)c.add("wco");})();`;

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${fontSans.variable} ${fontMono.variable} font-sans antialiased`}
			>
				<script
					// biome-ignore lint/security/noDangerouslySetInnerHtml: static pre-hydration script, no user input
					dangerouslySetInnerHTML={{ __html: DESKTOP_ROOT_CLASS_SCRIPT }}
				/>
				<DesktopClassSync />
				<ElectronWindow>
					<ConvexClientProvider>
						<ThemeProvider>
							<AuthProvider>
								<SetupGuard>
									<ConditionalUserMenu />
									{children}
								</SetupGuard>
							</AuthProvider>
						</ThemeProvider>
					</ConvexClientProvider>
				</ElectronWindow>
			</body>
		</html>
	);
}
