/**
 * Authentication/authorization error codes
 */
export const AUTH_ERROR_CODE = {
  AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
  CREATE_USER_FAILED: "CREATE_USER_FAILED",
  DELETE_USER_FAILED: "DELETE_USER_FAILED",
  DISPOSABLE_EMAIL: "DISPOSABLE_EMAIL",
  EMAIL_VERIFICATION_FAILED: "EMAIL_VERIFICATION_FAILED",
  GET_USER_FAILED: "GET_USER_FAILED",
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  RATE_LIMITED: "RATE_LIMITED",
  RESET_PASSWORD_FAILED: "RESET_PASSWORD_FAILED",
  SEND_VERIFICATION_EMAIL_FAILED: "SEND_VERIFICATION_EMAIL_FAILED",
  UNAUTHORIZED: "UNAUTHORIZED",
  UPDATE_USER_FAILED: "UPDATE_USER_FAILED",
} as const;
