/**
 * General error codes
 */
export const ERROR_CODE = {
	UNKNOWN: "UNKNOWN",
	INVALID_INPUT: "INVALID_INPUT",
	RATE_LIMITED: "RATE_LIMITED",
} as const;

/**
 * Authentication/authorization error codes
 */
export const AUTH_ERROR_CODE = {
	UNAUTHORIZED: "UNAUTHORIZED",
	DISPOSABLE_EMAIL: "DISPOSABLE_EMAIL",
	NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
	RATE_LIMITED: "RATE_LIMITED",
	AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
	CREATE_USER_FAILED: "CREATE_USER_FAILED",
	GET_USER_FAILED: "GET_USER_FAILED",
	UPDATE_USER_FAILED: "UPDATE_USER_FAILED",
	DELETE_USER_FAILED: "DELETE_USER_FAILED",
	EMAIL_VERIFICATION_FAILED: "EMAIL_VERIFICATION_FAILED",
	SEND_VERIFICATION_EMAIL_FAILED: "SEND_VERIFICATION_EMAIL_FAILED",
	RESET_PASSWORD_FAILED: "RESET_PASSWORD_FAILED",
} as const;

/**
 * User error codes
 */
export const USER_ERROR_CODE = {
	USER_NOT_FOUND: "USER_NOT_FOUND",
	USER_CREATE_FAILED: "USER_CREATE_FAILED",
	USER_UPDATE_FAILED: "USER_UPDATE_FAILED",
	USER_DELETE_FAILED: "USER_DELETE_FAILED",
} as const;

/**
 * Billing error codes
 */
export const BILLING_ERROR_CODE = {
	SUBSCRIPTION_CANCEL_FAILED: "SUBSCRIPTION_CANCEL_FAILED",
	CUSTOMER_DELETE_FAILED: "CUSTOMER_DELETE_FAILED",
	PRODUCTS_SYNC_FAILED: "PRODUCTS_SYNC_FAILED",
	CHECKOUT_FAILED: "CHECKOUT_FAILED",
} as const;

/**
 * Email error codes
 */
export const EMAIL_ERROR_CODE = {
	SEND_FAILED: "EMAIL_SEND_FAILED",
	INVALID_RECIPIENT: "EMAIL_INVALID_RECIPIENT",
} as const;

/**
 * User-facing error messages
 */
export const ERROR_MESSAGE = {
	UNAUTHORIZED: "You are not authorized to perform this action",
	NOT_AUTHENTICATED: "Please sign in to continue",
	USER_NOT_FOUND: "User not found",
	RATE_LIMITED: "Too many attempts. Please try again later",
	UNKNOWN: "Something went wrong. Please try again",
} as const;
