/**
 * General error codes
 */
export const ERROR_CODE = {
  INVALID_INPUT: "INVALID_INPUT",
  RATE_LIMITED: "RATE_LIMITED",
  UNKNOWN: "UNKNOWN",
} as const;

/**
 * Authentication/authorization error codes
 */
export const AUTH_ERROR_CODE = {
  AUTHENTICATION_FAILED: "AUTHENTICATION_FAILED",
  CREATE_USER_FAILED: "CREATE_USER_FAILED",
  DELETE_USER_FAILED: "DELETE_USER_FAILED",
  DISPOSABLE_EMAIL: "DISPOSABLE_EMAIL",
  EMAIL_VERIFICATION_FAILED: "EMAIL_VERIFICATION_FAILED",
  GET_USER_FAILED: "GET_USER_FAILED",
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  RATE_LIMITED: "RATE_LIMITED",
  RESET_PASSWORD_FAILED: "RESET_PASSWORD_FAILED",
  SEND_VERIFICATION_EMAIL_FAILED: "SEND_VERIFICATION_EMAIL_FAILED",
  UNAUTHORIZED: "UNAUTHORIZED",
  UPDATE_USER_FAILED: "UPDATE_USER_FAILED",
} as const;

/**
 * User error codes
 */
export const USER_ERROR_CODE = {
  USER_CREATE_FAILED: "USER_CREATE_FAILED",
  USER_DELETE_FAILED: "USER_DELETE_FAILED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_UPDATE_FAILED: "USER_UPDATE_FAILED",
} as const;

/**
 * Billing error codes
 */
export const BILLING_ERROR_CODE = {
  CHECKOUT_FAILED: "CHECKOUT_FAILED",
  CUSTOMER_DELETE_FAILED: "CUSTOMER_DELETE_FAILED",
  PRODUCTS_SYNC_FAILED: "PRODUCTS_SYNC_FAILED",
  SUBSCRIPTION_CANCEL_FAILED: "SUBSCRIPTION_CANCEL_FAILED",
} as const;

/**
 * Email error codes
 */
export const EMAIL_ERROR_CODE = {
  INVALID_RECIPIENT: "EMAIL_INVALID_RECIPIENT",
  SEND_FAILED: "EMAIL_SEND_FAILED",
} as const;

/**
 * User-facing error messages
 */
export const ERROR_MESSAGE = {
  NOT_AUTHENTICATED: "Please sign in to continue",
  RATE_LIMITED: "Too many attempts. Please try again later",
  UNAUTHORIZED: "You are not authorized to perform this action",
  UNKNOWN: "Something went wrong. Please try again",
  USER_NOT_FOUND: "User not found",
} as const;
